// Shim for the pre-compiled build. Do not edit.
// Generated by build/bundleDocsScripts.mjs from src/utils/sharedFileProcessorUtils.mjs.
// Edit that file, then run `npm run build:bundles`.
export * from "../../dist/utils/sharedFileProcessorUtils.mjs";
