name: Surge Teardown

on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    # run every month
    - cron: "0 0 1 * *"

jobs:
  surgeTeardown:
    name: Teardown
    runs-on: ubuntu-latest

    steps:
      - name: teardown
        uses: adrianjost/actions-surge.sh-teardown@master
        with:
          # teardown projects older than 2 months
          regex: '[2-9]+ months ago'
        env:
          SURGE_LOGIN: ${{ secrets.AURO_SURGE_LOGIN }}
          SURGE_TOKEN: ${{ secrets.AURO_SURGE_TOKEN }}
