name: Surge Teardown

on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    # run every month
    - cron: "0 0 1 * *"

jobs:
  surge-teardown:
    runs-on: ubuntu-latest
    steps:
      - name: teardown
        uses: adrianjost/actions-surge.sh-teardown
        with:
          # teardown projects older than 2 months
          regex: '[2-9]+ months ago'
          dryrun: true
        env:
          SURGE_LOGIN: "auro@alaskaair.com"
          SURGE_TOKEN: ${{ secrets.SURGE_TOKEN }}
